name: CI
on:
  pull_request:
  push:
    branches:
      - develop
      - feat/added-ci-workflow

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Run code formatting check
        run: npm run prettier

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Run lint check
        run: npm run build

